run_time_vars:
- name: PUBLIC_KEY
  source:
    path: api-node/config-input.yaml
    key: public_key
    address_position: 0 
    key_type: public
  targets:
  - rest-gateway/userconfig/rest.json
- name: HARVESTER_PRIVATE_KEY
  source:
    path: api-node/config-input.yaml
    key: harvester_private_key
    # this is placeholder
    address_position: 0 
    key_type: private
    donot_overwrite: true
  targets:
  - api-node/userconfig/resources/config-harvesting.properties
- name: HARVESTER_VRF_PRIVATE_KEY
  source:
    path: api-node/config-input.yaml
    key: harvester_vrf_private_key
    # this is placeholder
    address_position: 0 
    key_type: private
    donot_overwrite: true
  targets:
  - api-node/userconfig/resources/config-harvesting.properties
- name: FRIENDLY_NAME
  source:
    type: friendly_name
    path: api-node/config-input.yaml
    key: friendly_name
    address_position: 0 
    key_type: public
    donot_overwrite: true
  targets:
  - api-node/userconfig/resources/config-node.properties
